name: ajut-dev

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  deploy-ajut-dev:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_SSH_HOST }}
        username: ${{ secrets.DEPLOY_SSH_USERNAME }}
        password: ${{ secrets.DEPLOY_SSH_PASSWORD }}
        port: ${{ secrets.DEPLOY_SSH_PORT }}
        script: whoami && ls -lah && pwd
